name: deploy-container

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]
    paths:
      -'packages/container/**'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v2
      
    - name: install
      run: npm install
      
    - name: run build  
      run: npm run build
          
    - name: AWS
      uses: shinyinc/action-aws-cli@v1.2
    - run: aws s3 sync dist s3://${{ secrets.AWS_s3_DUCKET_NAME }}/container/latest
    - env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      
